services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        JWT_SECRET: ${JWT_SECRET}
        JWT_SECRET_REFRESH: ${JWT_SECRET_REFRESH}
        COOKIE_DOMAIN: ${COOKIE_DOMAIN}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge
